title: "Vukan Antić"
author: "Vukan Antić"
description: "@2022 Vukan Antić"
url: "vukanantic.gihub.io"
permalink: "/:Title/"
lang: "srb"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header (maybe use this)
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "Pocetna.md", title: "Početna"}
  - {file: "index.html", title: "Sve vesti"}
  - {file: "OOP.md", title: "OOP"}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/vukan-anti%C4%87/"}
  - {title: Github, icon: github, url: "https://github.com/VukanAntic"}
  - {title: Gitlab, icon: gitlab, url: "https://gitlab.com/VukanAntic"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}



comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
